services:
  api:
    build:
      context: .
      target: final
    ports:
      - 8085:8085
#    depends_on: 
#      sqlserver:
#        condition: service_started
    
    networks:
      - app-network
 
networks:
  app-network:
    external: true
#  sql-edge-container:
#    image: mcr.microsoft.com/azure-sql-edge
#    container_name: sql-edge
#    ports:
#      - 1431:1431
#    environment:
#      - ACCEPT_EULA=1
#      - MSSQL_SA_PASSWORD=Password_123
#      - MSSQL_PID=Developer
#      - MSSQL_USER=sa
#    volumes:
#      - ./data:/var/opt/mssql/data
#      - ./log:/var/opt/mssql/log